"""Record each frame's visible bottom so water crops don't just trim padding."""
from pathlib import Path
import sys
from PIL import Image

root = Path(__file__).resolve().parents[1]
lines = ["-- Generated by tools/build_water_bounds.py from supplied sprite alpha.",
         "return function() return {"]
count = 0
for path in sorted((root / 'assets').rglob('*.png')):
    with Image.open(path) as source:
        image = source.convert('RGBA')
        w, h = image.width // 4, image.height // 4
        rows = []
        for row in range(4):
            bottoms = []
            for frame in range(4):
                alpha = image.getchannel('A').crop((frame*w, row*h, (frame+1)*w, (row+1)*h))
                bounds = alpha.getbbox()
                bottoms.append(bounds[3] if bounds else 0)
            rows.append('{' + ','.join(map(str, bottoms)) + '}')
        lines.append("  ['" + path.relative_to(root).as_posix() + "']={" + ','.join(rows) + '},')
        count += 1
lines.append('} end')
output = '\n'.join(lines) + '\n'
target = root / 'src/water_bounds.lua'
if '--check' in sys.argv:
    assert target.read_text(encoding='utf-8') == output, 'Water alpha bounds are stale; regenerate them.'
else:
    target.write_text(output, encoding='utf-8')
print(f'PASS recorded visible bottoms for {count} sheets / {count*16} frames')
